name: Github Action Demo
run-name: Testing out Github Actions

on: [push]

jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
